name: Build image and push to ACR

permissions:
      id-token: write
      contents: read

on:
  push:
    tags:
      - '*'

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        environment: production
        steps:
        - name: 'Checkout repository'
          uses: actions/checkout@main
        - name: 'Set RELEASE_VERSION'
          run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
              client-id: ${{ secrets.AZURE_CLIENT_ID }}
              tenant-id: ${{ secrets.AZURE_TENANT_ID }}
              subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - name: 'Build image via ACR'
          run: |
            az acr build --image mood/updater:${{ env.RELEASE_VERSION }} \
              --resource-group ${{ secrets.RESOURCE_GROUP }} \
              --registry ${{ secrets.REGISTRY_NAME }} \
              --platform Linux/arm64 \
              --file Dockerfile .
